### ISSUE TITLE
Add createCollection and updateCollection for android clients 

### ISSUE THREAD

**Issue by anitaderiane** [wedeploy/wedeploy-sdk-android#11]
Hey @sgosantos, there are two new methods in JS API: `createCollection` and `updateCollection`.
[Here](https://github.com/wedeploy/api-js/commit/9fe04033ea0f75ed342db3d2ccd9789503b77e72) is the commit where they were added and [here](https://github.com/wedeploy/api-js/issues/185) is the issue where they were added, it explains their purpose.

Could you please add them?

I know you are already busy with the Liferay events app, and this is not a blocker for the WeDeploy Stable release, so let me know when you are able to work on it. 

Thanks,

**Comment by victorlaerte** [comment]
#16
