### ISSUE TITLE
Expose withCredentials

### ISSUE THREAD

**Issue by anitaderiane** [wedeploy/wedeploy-sdk-android#12]
Hi @sgosantos, 

Can you please have a look at this [enhancement](https://github.com/wedeploy/api-js/issues/189) in api-js and apply the same change in api-android?

If you have any question, you can ask @ipeychev. 

I know you are already busy to release the new version of Liferay Events app for DevCon, and this is not a blocker for our release, so let me know when you'll be able to work on this. 

Thank you.

**Comment by victorlaerte** [comment]
#14

**Comment by victorlaerte** [comment]
@ipeychev could you please take a look ? #14

**Comment by victorlaerte** [comment]
After discuss with @victorg1991 and @ipeychev [here](https://github.com/wedeploy/wedeploy-sdk-android/pull/14) we decided there's no need to implement withCredentials for android and swift clients
