### ISSUE TITLE
Add a new method `fields` for fetching only specified fields from the document

### ISSUE THREAD

**Issue by victorlaerte** [wedeploy/wedeploy-sdk-android#20]
We need to add a new method to Data, called ```fields```, where user will be able to specify which fields from the document in a collection should be fetched, instead to fetch always all fields.

**Comment by victorlaerte** [comment]
https://github.com/wedeploy/wedeploy-sdk-js/issues/236

**Comment by victorlaerte** [comment]
#22

**Comment by zenorocha** [comment]
🎉
