### ISSUE TITLE
Update API docs

### ISSUE THREAD

**Issue by victorlaerte** [wedeploy/wedeploy-sdk-android#26]
Reference https://github.com/wedeploy/wedeploy-sdk-js/pull/240

**Comment by anitaderiane** [comment]
Hello @victorlaerte, is this still in progress?

**Comment by victorlaerte** [comment]
hey @anitaderiane most have already been done and merged, but still some points to improve. I think we can leave this open for now, I'll try finish until next week.

**Comment by victorlaerte** [comment]
https://docs-androidsdkdocs.wedeploy.io/
