### ISSUE TITLE
Stacktrace error response is missing a line break

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/wedeploy-sdk-android#30]
![screenshot - 7_6_2018 10_28_48 am](https://user-images.githubusercontent.com/398893/43040558-7701de36-8cfb-11e8-826d-0500f4a33701.png)

> Originally reported at https://issues.liferay.com/browse/ASAH-178

**Comment by victorlaerte** [comment]
This is a server side problem, as you can see below the server is returning the message body missing a "\n".

<img width="1316" alt="screen shot 2018-07-23 at 10 30 05" src="https://user-images.githubusercontent.com/7623098/43080225-a0a87b3a-8e65-11e8-84f8-2db1dcba5759.png">

Curl request:
<img width="967" alt="screen shot 2018-07-23 at 10 38 24" src="https://user-images.githubusercontent.com/7623098/43080239-a65aaef4-8e65-11e8-98c1-4cd4a45398e4.png">

**Comment by zenorocha** [comment]
Thanks @victorlaerte!
